# Generated by Django 3.2.8 on 2021-10-18 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField()),
                ('street', models.TextField()),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'Address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13, verbose_name='Telephone Number')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('site', models.URLField(verbose_name='Provider Web Site')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Storages/commun/toys')),
                ('bought_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.provider')),
            ],
            options={
                'verbose_name': 'Toy',
                'verbose_name_plural': 'Toys',
                'db_table': 'Toy',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='toy.place')),
                ('toys', models.ManyToManyField(to='toy.Toy', verbose_name='Provided toys')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer_tab',
                'ordering': ['name', 'tel'],
                'managed': True,
            },
        ),
    ]
